# Recursive resolver for AdGuard Home upstream.
# https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html

server:
	do-daemonize: no
	username: "unbound"
	chroot: ""
	logfile: ""
	pidfile: ""
	verbosity: 1

	interface: 0.0.0.0
	port: 5053

	do-ip4: yes
	do-udp: yes
	do-tcp: yes
	do-ip6: no
	prefer-ip6: no

	harden-glue: yes
	harden-dnssec-stripped: yes
	use-caps-for-id: no
	edns-buffer-size: 1232
	prefetch: yes

	# Z2 Mini has spare cores
	num-threads: 2
	so-rcvbuf: 1m

	access-control: 127.0.0.1/32 allow
	access-control: 192.168.0.0/16 allow
	access-control: 172.16.0.0/12 allow
	access-control: 10.0.0.0/8 allow

	private-address: 192.168.0.0/16
	private-address: 169.254.0.0/16
	private-address: 172.16.0.0/12
	private-address: 10.0.0.0/8
	private-address: fd00::/8
	private-address: fe80::/10

	private-domain: plex.direct
	private-domain: nip.io

include-toplevel: "/etc/unbound/custom.conf.d/*.conf"
